#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.15.1"

# Site Settings
locale                   : "en-GB"
title                    : "Mainly Technical"
title_separator          : "-"
name                     : "Alex Vilela"
description              : "An amazing website."
url                      : "http://localhost"
#baseurl                  : # the subpath of your site, e.g. "/blog"
repository               : alexvilela/alexvilela.github.io
words_per_minute         : 200

# Social Sharing
twitter:
  username               : alexfoobar
#og_image                 : # Open Graph/Twitter default site image

# Site Author
author:
  name             : "Alex Vilela"
  # avatar           : # path of avatar image, e.g. "/assets/images/bio-photo.jpg"
  bio              : "I am an amazing person."
  location         : "London"
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alexfoobar"

# Site Footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/alexfoobar"

encoding: "utf-8"

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true